### ISSUE TITLE
What wayland to use for 1.6.0 WIP branches?

### ISSUE THREAD

**Issue by agherzan** [ntanibata/weston-ivi-shell#7]
I'm trying to compile weston-ivi-shell-1.6.0-WIP-14 with wayland 1.6 and it fails because commit 50b67479033709d8ab32744c7b8346b130ace9e0 introduces WL_SHELL_ERROR_ROLE which is not defined in wayland 1.6. Wasn't weston 1.6 supposed to be working with wayland 1.6?
Log:

data-device.c:673:10: error: 'WL_DATA_DEVICE_ERROR_ROLE' undeclared (first use in this function)
|           WL_DATA_DEVICE_ERROR_ROLE) < 0)
...
input.c:1641:10: error: 'WL_POINTER_ERROR_ROLE' undeclared (first use in this function)
|           WL_POINTER_ERROR_ROLE) < 0)

**Comment by agherzan** [comment]
Ping?

**Comment by ntanibata** [comment]
Sorry. I missed the comment. It seems to be bug. I will check it at first.

**Comment by agherzan** [comment]
Thank you. Waiting for your feedback.

**Comment by ntanibata** [comment]
Sorry for late.

Please use later version of
 wayland : 7a0b86a

It fixes protocol and you can avoid the above issue.
